# Generated by Django 5.0.1 on 2024-03-31 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_executor',
        ),
        migrations.AddField(
            model_name='task',
            name='task_executors',
            field=models.ManyToManyField(related_name='bajaruvchilar_tasklari', to=settings.AUTH_USER_MODEL),
        ),
    ]
