# Generated by Django 5.0.1 on 2024-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_task_task_executor_task_task_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryparams',
            name='kpi_by_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
