# Generated by Django 5.0.1 on 2024-04-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
