# Generated by Django 5.0.1 on 2024-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_salaryparams_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
