# Generated by Django 5.0.1 on 2024-05-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_amount_salarypayment_total_amount_and_more'),
        ('warehouses', '0005_alter_warehouseproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_set', to='warehouses.warehouse'),
        ),
    ]
