# Generated by Django 5.0.1 on 2024-05-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_car_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
