# Generated by Django 5.0.1 on 2024-05-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline', '-id']},
        ),
    ]
