# Generated by Django 5.0.1 on 2024-05-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id', '-deadline']},
        ),
    ]
