# Generated by Django 5.0.1 on 2024-03-05 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('location', models.JSONField()),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
