# Generated by Django 5.0.1 on 2024-03-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('warehouses', '0002_warehouseproduct_invalids_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstore',
            name='agent',
        ),
        migrations.AddField(
            model_name='customerstore',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse'),
        ),
    ]
