# Generated by Django 5.0.1 on 2024-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customerstore_agent_customerstore_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstore',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
