# Generated by Django 5.0.1 on 2024-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerstore_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstore',
            name='location',
        ),
        migrations.AddField(
            model_name='customerstore',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerstore',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
