# Generated by Django 5.0.1 on 2024-05-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customerstore_location_customerstore_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerstore',
            options={'ordering': ['name', 'address']},
        ),
    ]
