# Generated by Django 5.0.1 on 2024-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='invalids_amount',
            field=models.IntegerField(default=0),
        ),
    ]
