# Generated by Django 5.0.1 on 2024-03-31 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouseproduct_invalids_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
