# Generated by Django 5.0.1 on 2024-05-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
        ('warehouses', '0004_remove_warehouseproduct_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'product')},
        ),
    ]
