# Generated by Django 5.0.1 on 2024-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
