# Generated by Django 5.0.1 on 2024-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_warehouse_archived_warehouseproduct_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='total_sum',
            field=models.IntegerField(default=0),
        ),
    ]
