# Generated by Django 5.0.1 on 2024-06-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_rename_invalids_warehouseproductarrival_invalids_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'ordering': ['product__name', '-id']},
        ),
    ]
