# Generated by Django 5.0.1 on 2024-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Active', max_length=30),
        ),
    ]
