# Generated by Django 5.0.1 on 2024-05-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_kpiearning_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='warehouse_product',
        ),
    ]
