# Generated by Django 5.0.1 on 2024-06-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_total_price_order_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tot_price',
            field=models.BigIntegerField(),
        ),
    ]
