# Generated by Django 5.0.1 on 2024-05-22 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', '-id']},
        ),
    ]
